---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
- name: node-exporter-release
- name: pcf-prometheus-pipeline
- name: pcf-bosh-creds

params:
  director_for_deployment: 
    
run:
  path: pcf-prometheus-pipeline/pipeline/tasks/install-node-exporter.sh
